[package]
name = "coreboot-table"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"
description = "Coreboot Table Parser"
license = "MIT"

[dev-dependencies]
orbtk = "0.2"
